//
//  DogListInterfaces.swift
//  appkonfio
//
//  Created by Jorge on 11/11/19.
//  Copyright (c) 2019 pagatodo. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum DogListNavigationOption {
}

protocol DogListWireframeInterface: WireframeInterface {
    func navigate(to option: DogListNavigationOption)
}

protocol DogListViewInterface: ViewInterface {
    func setSourceDogsList(_ dogsList: [DogsObject])
}

protocol DogListPresenterInterface: PresenterInterface {
    func getDogList()
}

protocol DogListInteractorInterface: InteractorInterface {
    func getDogListAsync(onSuccess: @escaping ([DogsObject]) -> ())
}
