//
//  DogListWireframe.swift
//  appkonfio
//
//  Created by Jorge on 11/11/19.
//  Copyright (c) 2019 pagatodo. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DogListWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "DogList", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: DogListViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = DogListInteractor()
        let presenter = DogListPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension DogListWireframe: DogListWireframeInterface {

    func navigate(to option: DogListNavigationOption) {
    }
}
