//
//  DogListInteractor.swift
//  appkonfio
//
//  Created by Jorge on 11/11/19.
//  Copyright (c) 2019 pagatodo. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Moya

final class DogListInteractor {
}

// MARK: - Extensions -

extension DogListInteractor: DogListInteractorInterface {
    
    func getDogListAsync(onSuccess: @escaping ([DogsObject]) -> ()) {
        
        let provider = MoyaProvider<APIKonfio>()
        provider.request(.asyncDogList) { (result) in
            switch result{
            case .success(let response):
                do {
                    let results = try JSONDecoder().decode([DogsObject].self, from: response.data)
                    onSuccess(results)
                } catch let err {
                    print(err)
                }
                break
            case .failure(let error):
                print(error)
            }
        }
    }
}
