//
//  DogListPresenter.swift
//  appkonfio
//
//  Created by Jorge on 11/11/19.
//  Copyright (c) 2019 pagatodo. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DogListPresenter {

    // MARK: - Private properties -

    private unowned let _view: DogListViewInterface
    private let _wireframe: DogListWireframeInterface
    private let _interactor: DogListInteractorInterface

    // MARK: - Lifecycle -

    init(wireframe: DogListWireframeInterface, view: DogListViewInterface, interactor: DogListInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension DogListPresenter: DogListPresenterInterface {
    func getDogList() {
        _interactor.getDogListAsync { (dogsList) in
            self._view.setSourceDogsList(dogsList)
        }
    }
}
